### ISSUE TITLE
Design Return Policy Page, About us, Sellers Policy, terms and conditions, Privacy Policy, and Support Policy page

### ISSUE THREAD

**Issue by iamkelv** [africommerce/africommerce-saas#10]
**Design Return Policy Page, About us, Sellers Policy, terms and conditions, Privacy Policy, and Support Policy page**
This pages Navs are on the Footer section and the file are found in the pages folder.
The template design can be found @ https://demo.activeitzone.com/ecommerce/ Footer Section

**Comment by debbyuzuegbu** [comment]
I would like to work on the about us page, sellers policy and privacy policy

**Comment by iamkelv** [comment]
@debbyuzuegbu  you have been assigned all the Return Policy Page, About us, Sellers Policy, terms and conditions, Privacy Policy, and Support Policy page
