### ISSUE TITLE
Admin OPT System

### ISSUE THREAD

**Issue by iamkelv** [africommerce/africommerce-saas#119]

**Comment by Sodeeqishola5** [comment]
Can u assign this for me?

**Comment by iamkelv** [comment]
Thank you @Sodeeqishola5  you can go ahead

**Comment by iamkelv** [comment]
https://demo.activeitzone.com/ecommerce/admin

**Comment by Sodeeqishola5** [comment]
Ok good.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
