### ISSUE TITLE
HOME PAGE RESPONSIVE ON ALL DEVICES

### ISSUE THREAD

**Issue by iamkelv** [africommerce/africommerce-saas#13]
The website Home page is not responsive on all devices make it responsive on all devices.
The Home page is located in the pages folder

**Comment by 0xlarmideh** [comment]
If nobody is working on this, let me work on this first as this is more important.

**Comment by iamkelv** [comment]
@0xlarmideh  you can go ahead the task dateline is 3 day's.

**Comment by 0xlarmideh** [comment]
Perfect

**Comment by 0xlarmideh** [comment]
My commit will be done today.

**Comment by iamkelv** [comment]
Pls try and do that before the meeting time
