### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by iamkelv** [africommerce/africommerce-saas#14]
We need someone who can work on our documentation

**Comment by oyin-systems** [comment]
I'm interested

**Comment by Sodeeqishola5** [comment]
I can handle client page issue

**Comment by iamkelv** [comment]
@Sodeeqishola5  it has already been asigned

**Comment by Sodeeqishola5** [comment]
@iamkelv so, which issue de on ground i can work on. Could you list them make i see?

**Comment by Sodeeqishola5** [comment]
Could you list those issues wey dey available

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Sodeeqishola5** [comment]
Hello I'm working with frontend team Admin Dashboard, I was assign to sales issue.

**Comment by iamkelv** [comment]
@oyin-systems Can you pls give us feedback on your progress?

**Comment by debbyuzuegbu** [comment]
@Sodeeqishola5 view all issues from the repo

**Comment by debbyuzuegbu** [comment]
@oyin-systems Hello, have you completed this issue? any blockers?
