### ISSUE TITLE
Implement ALL BRAND API 

### ISSUE THREAD

**Issue by iamkelv** [africommerce/africommerce-saas#153]
Hey, @ufomaodufejo  hope you're well. this was the issue assigned to you to work on and implement all the API relating to the all-brand page and in case you notice an issue with API then you can raise the issue in the group. 
Waiting for you reply.
**Thank you .**

**TAKE NOTE OF THE DUE DATE**

**Comment by HedrisTemmyTop** [comment]
Is this done already ?
