### ISSUE TITLE
Design a good All Categories page

### ISSUE THREAD

**Issue by iamkelv** [africommerce/africommerce-saas#21]
**Design a good All category page**

The  demo template is shown below  https://demo.activeitzone.com/ecommerce/brands

let's know if you need more information 

NOTE: the page file is located in the pages folder

**Comment by alvinokafor** [comment]
I would like to work on this

**Comment by iamkelv** [comment]
@alvinokafor  you can go on. the date line is tomorrow

**Comment by alvinokafor** [comment]
@iamkelv Just to clarify, for this task i just need to replicate the all categories page from the demo link right?

**Comment by iamkelv** [comment]
@alvinokafor  Yes

**Comment by alvinokafor** [comment]
ok, thanks
