### ISSUE TITLE
Design Coupon Page 

### ISSUE THREAD

**Issue by iamkelv** [africommerce/africommerce-saas#23]
**Design Coupon Page** 

Design as demo template @ https://demo.activeitzone.com/ecommerce/coupons

This file is found in the pages folder

**Comment by oyinmi** [comment]
I'll like to work on this please. Kindly assign this to me.

**Comment by iamkelv** [comment]
@oyinmi  you can go on the dateline is today.

**Comment by iamkelv** [comment]
@oyinmi  has been assigned the issue

**Comment by iamkelv** [comment]
@oyinmi  can you pls give us progress feedback on the issue assigned to you. Thank you

**Comment by debbyuzuegbu** [comment]
@oyinmi Hello, have you completed this issue? any blockers?

**Comment by oyinmi** [comment]
Hi Africommerce/Africommerce-Saas

I dropped out of the program already about 3 weeks ago now and so I didn’t
work on the issue.

Thank you

**Comment by iamkelv** [comment]
Hey, @oyinmi  Thank you for your time. We really appreciate all your efforts.

**Comment by iamkelv** [comment]
Hey, @oyinmi  Thank you for your time. We really appreciate all your efforts.
