### ISSUE TITLE
Create a folder and .jsx files on users dashboard

### ISSUE THREAD

**Issue by debbyuzuegbu** [africommerce/africommerce-saas#25]
create a folder, name it users and then add file login.jsx, dashboard.jsx, downloads.jsx, sent.jsx, wishlist.jsx, compare.jsx, classified.jsx, auction.jsx, conversation.jsx, wallet.jsx, earning.jsx, affliate.jsx, support.jsx, manage.jsx.

**Comment by ShedrachJonah11** [comment]
I'd like to work on this issue.

**Comment by debbyuzuegbu** [comment]
Great you can go ahead and work on this

**Comment by ufomaodufejo** [comment]
id like to work on the dashboard

**Comment by iamkelv** [comment]
@ShedrachJonah11  can you pls give us progress feedback on the issue assigned to you. Thank you

**Comment by iamkelv** [comment]
> id like to work on the dashboard

Thank you for your interest can you pick another issue?

**Comment by debbyuzuegbu** [comment]
Please check your WhatsApp

**Comment by debbyuzuegbu** [comment]
@ShedrachJonah11  Thank you Sheddy for the help.
