### ISSUE TITLE
Purchase folder

### ISSUE THREAD

**Issue by debbyuzuegbu** [africommerce/africommerce-saas#27]
purchase.jsx 
https://demo.activeitzone.com/ecommerce/purchase_history

**Comment by HedrisTemmyTop** [comment]
i'd like to work on this issue

**Comment by debbyuzuegbu** [comment]
Great, This issue has been assigned to you.

**Comment by iamkelv** [comment]
@HedrisTemmyTop  can you pls give us progress feedback on the issue assigned to you. Thank you
