### ISSUE TITLE
sent refund request

### ISSUE THREAD

**Issue by debbyuzuegbu** [africommerce/africommerce-saas#28]
sent.jsx
https://demo.activeitzone.com/ecommerce/sent-refund-request

**Comment by ufomaodufejo** [comment]
Id like to work on the refund request

**Comment by debbyuzuegbu** [comment]
Hello Ufoma, , this issue has been assigned to you.

**Comment by debbyuzuegbu** [comment]
Hello @ufomaodufejo Kindly do a pull request. Thank you
