### ISSUE TITLE
DESIGN ADMIN DASHBOARD SIDE NAV

### ISSUE THREAD

**Issue by iamkelv** [africommerce/africommerce-saas#29]

**Comment by Sodeeqishola5** [comment]
I can handle wholesales products page

**Comment by iamkelv** [comment]
Thank you @Sodeeqishola5  this has already been done can you chooses another issue?

**Comment by Sodeeqishola5** [comment]
Ok, sales page had been assigned for me

**Comment by iamkelv** [comment]
> Ok, sales page had been assigned for me

ok
