### ISSUE TITLE
Wallet Page

### ISSUE THREAD

**Issue by debbyuzuegbu** [africommerce/africommerce-saas#31]
wallet.jsx
https://demo.activeitzone.com/ecommerce/wallet

**Comment by DaraUkpong** [comment]
I want to work on this page.

**Comment by debbyuzuegbu** [comment]
Great this issue has been assigned to you

**Comment by iamkelv** [comment]
@DaraUkpong  How far have you gone with the issue?

**Comment by debbyuzuegbu** [comment]
@DaraUkpong any update on this issue?

**Comment by debbyuzuegbu** [comment]
@HedrisTemmyTop Assigning this to you. We would talk during our meeting
