### ISSUE TITLE
Earning 

### ISSUE THREAD

**Issue by debbyuzuegbu** [africommerce/africommerce-saas#37]
earning.jsx
https://demo.activeitzone.com/ecommerce/earning-points

**Comment by estherbabe** [comment]
hi, pls i'd like to work on earning

**Comment by debbyuzuegbu** [comment]
Great, it is assigned to you.

**Comment by iamkelv** [comment]
@estherbabe  how far have you gone with the issue?

**Comment by estherbabe** [comment]
Good morning Kelvin,

I am currently working on it, that's the earning page but there's no place
to put the route

**Comment by debbyuzuegbu** [comment]
Please check the master route

**Comment by estherbabe** [comment]
Thanks, I'll check it out.

**Comment by debbyuzuegbu** [comment]
@estherbabe  did you later work on this issue?
