### ISSUE TITLE
manage profile

### ISSUE THREAD

**Issue by debbyuzuegbu** [africommerce/africommerce-saas#39]
manage.jsx
https://demo.activeitzone.com/ecommerce/profile

**Comment by bolutej** [comment]
Hello i would love to be assigned the issue

**Comment by debbyuzuegbu** [comment]
@bolutej Hello Teju, any update on this issue?

**Comment by bolutej** [comment]
i am working on it but my laptop had some issues but i almost done with it
though

**Comment by debbyuzuegbu** [comment]
Hi @ufomaodufejo any update on this. Thank you
