### ISSUE TITLE
Products page

### ISSUE THREAD

**Issue by alvinokafor** [africommerce/africommerce-saas#46]
Create the product page and it's sub pages with the design from the demo link: https://demo.activeitzone.com/ecommerce/admin

**Comment by iamkelv** [comment]
I'll like to work on this issue can you please assign it to me?

**Comment by debbyuzuegbu** [comment]
@iamkelv  Hello, have you completed this issue? any blockers?

**Comment by iamkelv** [comment]
Hey, @debbyuzuegbu Yes it has been done and will be merged today. Thank you
