### ISSUE TITLE
Sales page

### ISSUE THREAD

**Issue by alvinokafor** [africommerce/africommerce-saas#49]
Create the sales page for the admin dashboard and it's sub pages using the design from the demo site: https://demo.activeitzone.com/ecommerce/admin

**Comment by Sodeeqishola5** [comment]
Pls assign this for me

**Comment by Sodeeqishola5** [comment]
Thank u very much

**Comment by debbyuzuegbu** [comment]
@Sodeeqishola5 Hello, have you completed this issue? any blockers?

**Comment by Sodeeqishola5** [comment]
It remain small

**Comment by Sodeeqishola5** [comment]
It's remain small...

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
