### ISSUE TITLE
Delivery boy page

### ISSUE THREAD

**Issue by alvinokafor** [africommerce/africommerce-saas#50]
Create the delivery boy page for the admin dashboard and it's sub pages using the design from the demo site: https://demo.activeitzone.com/ecommerce/admin

**Comment by charlesik** [comment]
I'll working on this issue

**Comment by debbyuzuegbu** [comment]
@charlesik any update on this?

**Comment by iamkelv** [comment]
Hey @charlesik , hope you're good pls are you still interest on this issue? thank you
