### ISSUE TITLE
Seller Upload Page

### ISSUE THREAD

**Issue by IbrahimO123** [africommerce/africommerce-saas#55]
## Create the seller upload page

This is the link to check out the design
https://demo.activeitzone.com/ecommerce/seller/uploads

**Comment by bolutej** [comment]
I would love to be asigned this issue

**Comment by IbrahimO123** [comment]
Great @bolutej You can work on it....

**Comment by debbyuzuegbu** [comment]
@bolutej Hello, have you completed this issue? any blockers?

**Comment by IbrahimO123** [comment]
@bolutej Thanks for this, And I hope we learned one or two things from it
