### ISSUE TITLE
Seller Orders Page

### ISSUE THREAD

**Issue by IbrahimO123** [africommerce/africommerce-saas#57]
## Create the seller order Page
This is the design to implement 
https://demo.activeitzone.com/ecommerce/seller/orders

**Comment by bolutej** [comment]
Hello ibrahim i would love to work on this page

**Comment by IbrahimO123** [comment]
Great Bolu, you can start working on this

**Comment by abd123codes** [comment]
BEAUTIFUL

**Comment by abd123codes** [comment]
if you need any help @bolutej you could reach out to me.
