### ISSUE TITLE
Seller Shop Settings Page

### ISSUE THREAD

**Issue by IbrahimO123** [africommerce/africommerce-saas#58]
## Create the Seller Shop page
This is the link for the design to implement
https://demo.activeitzone.com/ecommerce/seller/shop

**Comment by Adam-Thometz** [comment]
I could work on this but I get a 404

**Comment by IbrahimO123** [comment]
Great @Adam-Thometz  you can start working on it.. I will share a link with, you will need to click on the seller credential and navigate to the shop settings page

**Comment by IbrahimO123** [comment]
![shopsetting](https://user-images.githubusercontent.com/80628436/200675704-4d247aae-b122-41b7-a58f-c594dc85ad82.png)


https://demo.activeitzone.com/ecommerce/dashboard

That the link....you are only going to design the ones inside the red marker
someone is already working on the header and sidedraw
And you will need to attend our selller design meeting so I can explain the structure of the folder that we work with

**Comment by Adam-Thometz** [comment]
Sounds good.

**Comment by debbyuzuegbu** [comment]
@Adam-Thometz Hello, have you completed this issue? any blockers?

**Comment by Adam-Thometz** [comment]
Hello @debbyuzuegbu, sorry for the late response, I've been swamped by a lot of things on my end. I noticed that there are no components made for the input, even though there's a file for it located under ui-components. I could put this issue on hold and build the input component instead

**Comment by IbrahimO123** [comment]
There is.
Check your src folder , then open your pages folder, then your seller folder, then inside the seller folder you will see some file, the one with the name SellerShop is the one created for this issue
For you to view what you are doing, You will have to manually type /auth-seller to your localhost home page
Then from the sidebar you click on shop setting
I believe you still have the link to the design in case not: 
- https://demo.activeitzone.com/ecommerce/dashboard 
and click on seller credentials and do the same as above to view the design we are implementing  

![sellerShop](https://user-images.githubusercontent.com/80628436/203227061-a46e5ce3-08a2-4762-841c-19ff924eeedd.png)

**Comment by Adam-Thometz** [comment]
I was actually talking about src/components/ui components/input.jsx
![Screen Shot 2022-11-22 at 5 15 01 PM](https://user-images.githubusercontent.com/59377494/203432980-238aaa2e-4df3-4841-8956-6cbd541b1e9f.png)

Are there any plans for that file? If you need, I could flesh out the input component, which would make developing the SellerSettings component easier
