### ISSUE TITLE
Selller Products Page

### ISSUE THREAD

**Issue by IbrahimO123** [africommerce/africommerce-saas#59]
## Create the seller products page
this is the link for the design to implement
https://demo.activeitzone.com/ecommerce/seller/products

**Comment by alialaba** [comment]
Will like to work on this

**Comment by IbrahimO123** [comment]
Great....I have assigned it to you AbdulGaniy

**Comment by debbyuzuegbu** [comment]
@alialaba any update on this?

**Comment by IbrahimO123** [comment]
@alialaba Thanks for the completion
