### ISSUE TITLE
Design Flash Sale Page and Blog Page

### ISSUE THREAD

**Issue by iamkelv** [africommerce/africommerce-saas#6]
**Design Flash Sale Page and Blog Page**

The page routes has already been create on [loca](http://localhost:3000/blog  and /flash-sale

The template for the design can be found @ https://demo.activeitzone.com/ecommerce/flash-deals
and https://demo.activeitzone.com/ecommerce/blog

**Comment by IbrahimO123** [comment]
I will like to work on this...

**Comment by iamkelv** [comment]
@IbrahimO123  you can go on with the issue.

**Comment by HedrisTemmyTop** [comment]
i'd like to work on this issue.
