### ISSUE TITLE
Login page for Users Dashboard

### ISSUE THREAD

**Issue by debbyuzuegbu** [africommerce/africommerce-saas#63]

**Comment by ShedrachJonah11** [comment]
i'd like to work on this issue.

**Comment by iamkelv** [comment]
@ShedrachJonah11  how far have you gone?

**Comment by ShedrachJonah11** [comment]
Created the page, commit and push it's what's left.

**Comment by debbyuzuegbu** [comment]
@ShedrachJonah11  any update on this?

**Comment by ShedrachJonah11** [comment]
Not yet sorry for the delay
