### ISSUE TITLE
Design All Brands and all categories Page

### ISSUE THREAD

**Issue by iamkelv** [africommerce/africommerce-saas#7]
**Design All Brands and all categories Page**

Design the all brand page and All Category page 

**NOTE** :  the pages has already been created and you find them in the pages folder 
and you can view the page by clicking on the page from the nav bar

The Templates for this design can be found @ https://demo.activeitzone.com/ecommerce/brands and https://demo.activeitzone.com/ecommerce/categories

**Comment by alialaba** [comment]
Will like to work on this issue

**Comment by iamkelv** [comment]
@alialaba you can go on with the issue
