### ISSUE TITLE
Add Products Section

### ISSUE THREAD

**Issue by africommerce** [africommerce/africommerce-saas#7]
**Add Products Section**
Add a section that will hold the multiple product. this should be reusable in line with our contribution guide

**Comment by OscarMesh** [comment]
More details on this will be needed, I am interested

**Comment by IbrahimO123** [comment]
I will like to work on this issue

**Comment by africommerce** [comment]
@OscarMesh  Ok the Product section will be reusable UI component as in the image below
![product](https://user-images.githubusercontent.com/115594033/195394748-dc640c42-a08e-4ec6-aa47-c64739aab6d6.png)
are seen above. since we'll be having multiple product section we can use be reusing same Product component and customizing it.

**Comment by africommerce** [comment]
@IbrahimO123  and @OscarMesh  you can still check the link in the group to see how the section is
