### ISSUE TITLE
Design All Sellers page and Coupons Pages

### ISSUE THREAD

**Issue by iamkelv** [africommerce/africommerce-saas#8]
**Design All Sellers page and Coupons Pages**

These pages are already created in the pages folder.
you are to design the pages the template design is found @ https://demo.activeitzone.com/ecommerce/sellers and https://demo.activeitzone.com/ecommerce/coupons

**Comment by 0xlarmideh** [comment]
Would like to work on this.

**Comment by 0xlarmideh** [comment]
Would like to work on this.

**Comment by HedrisTemmyTop** [comment]
I'd like to work on this issue
