### ISSUE TITLE
Seller Review Page

### ISSUE THREAD

**Issue by IbrahimO123** [africommerce/africommerce-saas#89]
### Products Review
For members working with me, kindly use the design link I shared to see the design we are to implement for this page

**Comment by bolutej** [comment]
Hello ibrahim i would love to work on this review page

**Comment by IbrahimO123** [comment]
@bolutej I will have assigned this to you but someone is already working on it (all the product page menu), and I don't want you to rework this, since we have other pending issues, you can select another and I will assigned them to you,
Thanks for the understanding and cooperation

**Comment by alialaba** [comment]
Will like to work on this issue please do assign it to me.

**Comment by IbrahimO123** [comment]
You can start working on it Ganiy

**Comment by IbrahimO123** [comment]
@alialaba Welldone for the work...
